# Generated by Django 4.1.6 on 2023-02-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('lenght', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', editable=False, unique=True)),
            ],
        ),
    ]
