# Generated by Django 4.1.6 on 2023-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='medium',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
